{{- range $secret, $spec := .Values.argocd.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret }}
{{- if $spec.type }}
type: {{ $spec.type }}
{{- end }}
{{- if $spec.stringData }}
stringData:
{{ range $name, $value := $spec.stringData }}
  {{ $name }}: {{ $value }}
{{- end }}
{{- end }}
{{- end }}
