{{- range $project, $spec := .Values.argocd.projects }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $project }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: {{ $spec.description | default "TBP" }}
  sourceRepos:
    - '*'
  destinations:
    - name: in-cluster
      namespace: argocd
    {{- range $dest := $spec.destinations }}
    - namespace: {{ $dest.namespace }}
      name: {{ $dest.name | default "in-cluster" }}
    {{- end }}
  clusterResourceWhitelist:
    - group: '*'
      kind: 'Namespace'
    {{- range $resource := $spec.clusterResourceWhitelist | default list }}
    - group: {{ $resource.group }}
      kind: {{ $resource.kind }}
    {{- end }}
{{- end }}
