{{- range $sc, $spec := .Values.argocd.storageclasses }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $sc }}
provisioner: {{ $spec.provisioner }}
{{- if $spec.parameters }}
parameters:
   {{- range $name, $value := $spec.parameters }}
   {{ $name }}: {{ $value }}
   {{- end }}
{{- end }}
reclaimPolicy: {{ $spec.reclaimPolicy | default "Delete" }}
volumeBindingMode: {{ $spec.volumeBindingMode | default "Immediate" }}
allowVolumeExpansion: {{ $spec.allowVolumeExpansion | default true }}
{{- if $spec.mountOptions }}
mountOptions:
    {{- range $name, $value := $spec.mountOptions }}
    {{- if eq $value "present" }}
    - {{ $name }}
    {{- else }}
    - {{ $name }}={{ $value }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
